### ISSUE TITLE
unable to get data from content get an error No subscription found for the specified content type

### ISSUE THREAD

**Issue by RiddhiKarani** [OfficeDev/O365-InvestigationTooling#1]
i ran the PS on my tenant where i have configured the Azure app id and secret.
i get an error "error":{"code":"AF20022","message":"No subscription found for the specified content type."
i m trying to do this for sharepoint

**Comment by bkoeller** [comment]
Hey RiddhiKarani,
Couple of quick questions to help troubleshoot:
1. Did you populate the config file with the tenantid, appid, and app secret? Can you tell if the script is pulling the config values?
2. Did you grant your app in AD the correct claims to access the management activity api?
3. Is the app id registered in the same tenant that you are trying to pull the data from?

Detailed instructions on how to register the application are here: https://msdn.microsoft.com/EN-US/library/office/dn707383.aspx. 

Thanks,
Brandon

**Comment by RiddhiKarani** [comment]
yes, i have just not configured a webhook nor certificate for service to service calls.

rest everything is as per that blog, finally got this working.

any reason you are making call for every hour? cant we do one call for a day and still get same data?

**Comment by bkoeller** [comment]
Hi RiddhiKarani! Glad you got it working. The main reason for building a call set by the hour is mostly to get it to work against very large tenancies that have large volumes of data. Early versions of the API had trouble with the paging feature that would return results with a reference to a subsequent page of blobs if there were more. Cranking the pulls down to an hour allowed me to iterate more quickly for troubleshooting. :)  You are correct that you'll get the same data by making a call for a full day!
Thanks,
Brandon

**Comment by RiddhiKarani** [comment]
great, one more query have you tried adding the webhook and subscribing as a listener to the API?

**Comment by bkoeller** [comment]
Hi RiddhiKarani. Thanks for the follow-up. We have certainly tested the webhook subscription model, and we have many consumers that leverage the model. We did not implement a listener service in Powershell, however. If you have a managed code solution, the listener piece should be pretty straightfoward. Thanks! Brandon

**Comment by RiddhiKarani** [comment]
do you have any sample for the code solution with webhook for management api?

**Comment by RiddhiKarani** [comment]
i updated the powershell script to include webhook but the response output i get shows null for webhook.

$headerParams  = @{'Authorization'="$($oauth.token_type) $($oauth.access_token)"}

$webhook=@"
{
    "webhook" : {
        "address": "https://o365managementapiwebhook.azurewebsites.net/",
        "authId": "o365activityapinotification",
        "expiration": ""
    }
    }
"@



$jsonbody = $webhook | ConvertTo-Json

  Invoke-RestMethod -Method Post -Headers $headerParams -Uri "https://manage.office.com/api/v1.0/$tenantGUID/activity/feed/subscriptions/start?contentType=Audit.SharePoint" -Body $jsonbody 

this is the output i get
contentType                                                          status                                                              webhook                                                            
-----------                                                          ------                                                              -------                                                            
Audit.SharePoint                                                     enabled
