### ISSUE TITLE
Possible Copy and Paste Error

### ISSUE THREAD

**Issue by neocyber** [OfficeDev/O365-InvestigationTooling#16]
CreateAndSetPasswordsInBulk.ps1

# Should not be $user.Object - The below issue will loop through the same user every iteration
`foreach ($guid in $UserGuids)
{
       Write-Output "Setting the password for " $user.ObjectId;
	Set-MsolUserPassword –ObjectId $user.ObjectId –NewPassword $user.NewPassword -ForceChangePassword $True
}`

# Should be $guid .Object
`foreach ($guid in $UserGuids)
{
	Write-Output "Setting the password for " $guid.ObjectId;
	Set-MsolUserPassword –ObjectId $guid.ObjectId –NewPassword $guid.NewPassword -ForceChangePassword $True
}`

**Comment by mcvic1rj** [comment]
@bkoeller your previous commit fixes this issue. Can you close it?

**Comment by neocyber** [comment]
Thanks for the quick response. Issue has been resolved, closing
