### ISSUE TITLE
New to PowerShell - my report isn't generating

### ISSUE THREAD

**Issue by Lroberts2007** [OfficeDev/O365-InvestigationTooling#20]
I'm executing the code as defined and I'm not getting any errors, however, my two reports aren't generating anywhere. Am I missing something?

**Comment by mcvic1rj** [comment]
@Lroberts2007 Will need more information to help. What script are you running? What happens if you set $VerbosePreference to 'Continue' and run the script again?

**Comment by Lroberts2007** [comment]
Hello,

I tried this again this morning and it worked so I’m going to assume it was a server/AD issue.

Thank you!

Lynda Roberts
Director of Information Technology
DASCO Home Medical Equipment
Tele 614•901•2148  |  Fax 614•388•5849 |  Cell 740•361•0481

Notice: All email correspondence is subject to the following disclaimer http://www.godasco.com/terms.html

**Comment by mcvic1rj** [comment]
Please do not forget to close your issue as you have solved the problem.

**Comment by Lroberts2007** [comment]
Done, thank you!

Lynda Roberts
Director of Information Technology
DASCO Home Medical Equipment
Tele 614•901•2148  |  Fax 614•388•5849 |  Cell 740•361•0481

Notice: All email correspondence is subject to the following disclaimer http://www.godasco.com/terms.html
