### ISSUE TITLE
Update to mailbox auditing config doesn't work using Mac OS X powershell

### ISSUE THREAD

**Issue by peterwake** [OfficeDev/O365-InvestigationTooling#26]
Following recommendation from `https://securescore.office.com/#!/dashboard` I went to `https://github.com/OfficeDev/O365-InvestigationTooling/blob/master/EnableMailboxAuditing.ps1` and then installed powershell for Mac. Would have been good if it mentioned that this doesn't work! I guess related to `https://github.com/PowerShell/PowerShell/issues/3708` but not sure.

**Comment by mcvic1rj** [comment]
What is the specific error you are receiving? 

Last I tried, you can connect to office365 EXO from pwsh on Mac/Linux as long as you are not using MFA.

**Comment by peterwake** [comment]
@mcvic1rj that would be it. I just turned on MFA as part of the Secure Score work! Can I use an 'app password'..? as defined at https://account.activedirectory.windowsazure.com/AppPasswords.aspx

**Comment by peterwake** [comment]
It does work with an 'app password'. Apart from the Out-Gridview bit, which said it was not recognised (but I don't think this matters).

**Comment by mcvic1rj** [comment]
`Out-GridView` was something that was not brought over to pwsh v6. With this script there are a few options to make it cross compatible:
* Remove the “Verify” Section
* Rebuild the “Verify” Section to support pwsh v6 (possibly exporting the list as a CSV)
* Ignore this problem until `Out-GridView` is supported in pwsh v6 [issue 3957](https://github.com/PowerShell/PowerShell/issues/3957)

What option above do you think would fix this issue for you?

**Comment by peterwake** [comment]
I just removed the `| Out-GridView` bit and it worked fine :)
